In [1]:
import numpy as np
from random import randint

In [2]:
l1=[]
for _ in range(100_000_000):
    l1.append(randint(1,100))

toplam=0
for i in l1:
    toplam+=i

print(toplam)

5049659043


In [3]:
l2=np.random.randint(1,100,size=10_000_000)
print(l2.sum())

500058810


In [7]:
# numpy veritipi ndarray( n dimension array, çok boyutlu dizi)
nd1=np.array([3,5,8,10])
print("size=",nd1.size)
print("shape=",nd1.shape)
print("ndim=",nd1.ndim)

size= 4
shape (4,)
ndim 1


In [17]:
nd2=np.array([[17,21,35],[30,20,55]])
print("size=",nd2.size)
print("shape=",nd2.shape)
print("ndim=",nd2.ndim)
print("en büyük=",nd2.max())
print("en küçük",nd2.min())
print("toplam",nd2.sum())
print("nd2*3=",nd2*3)
print("nd2/3=",nd2/3)
print("nd2 deverik(transpoze)\n",nd2.T)
print("nd2 deverik(transpoze)\n",nd2.T.shape)

size= 6
shape= (2, 3)
ndim= 2
en büyük= 55
en küçük 17
toplam 178
nd2*3= [[ 51  63 105]
 [ 90  60 165]]
nd2/3= [[ 5.66666667  7.         11.66666667]
 [10.          6.66666667 18.33333333]]
nd2 deverik(transpoze)
 [[17 30]
 [21 20]
 [35 55]]
nd2 deverik(transpoze)
 (3, 2)
