In [44]:
# telefon_fiyati_regresyon.ipynb
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [45]:
veri = pd.read_csv("telefon_fiyatlari.csv")
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza    Ekran Tipi   Fiyat
0            T1               4            128  SUPER AMOLED  3300.0
1            T2               6            256        AMOLED  4400.0
2            T3               4            128        AMOLED  2700.0
3            T4               6            128           IPS  3600.0
4            T5               6             64           IPS  3200.0
5            T6               8            128  SUPER AMOLED  4100.0
6            T7               4             64        AMOLED  2400.0
7            T8               4             64  SUPER AMOLED  3000.0
8            T9               8            256           IPS  4200.0
9           T10               6            256           IPS     NaN
10          T11               8            128        AMOLED     NaN

In [46]:
veri["Ekran Tipi"].replace(to_replace=["SUPER AMOLED","AMOLED","IPS"],value=[3,2,1],inplace=True)
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza  Ekran Tipi   Fiyat
0            T1               4            128           3  3300.0
1            T2               6            256           2  4400.0
2            T3               4            128           2  2700.0
3            T4               6            128           1  3600.0
4            T5               6             64           1  3200.0
5            T6               8            128           3  4100.0
6            T7               4             64           2  2400.0
7            T8               4             64           3  3000.0
8            T9               8            256           1  4200.0
9           T10               6            256           1     NaN
10          T11               8            128           2     NaN

In [47]:
# sklearn 2 boyutlu numpy dizileri ile çalışır onun için değerlerin values kısmı alınır
#eğitimde kullanılacak X ve y değerleri
x_egitim=veri.iloc[0:9,1:4].values
y_egitim=veri.iloc[0:9,4].values.reshape(-1,1)
#tahmin edilecek x  değeri
x_tahmin=veri.iloc[9:,1:4].values

In [48]:
lr=LinearRegression()# doğrusal regresyon analizi için lr nesnesi oluşturuldu
lr.fit(x_egitim,y_egitim) # lr nesnesine ait fit methodu ile x ve y değerleri kullanılarak eğitim yapıldı.

LinearRegression()

In [49]:
# f(x)=ax1+bx2+cx3+d
print(lr.coef_)#[a,b,c]
print(lr.intercept_)# d değeri

[[251.78571429   4.85491071 171.42857143]]
[1035.71428571]


In [50]:
lr.predict([[8,256,3]])

array([[4807.14285714]])

In [51]:
lr.predict(x_tahmin)

array([[3960.71428571],
       [4014.28571429]])